### ISSUE TITLE
Direct assignment

### ISSUE THREAD

**Issue by haringsrob** [WendellAdriel/laravel-lift#1]
When directly assigning to a property it does not seem to set the attribute.

Example:

$someModel->some_field = 5;
$someModel->save();

**Comment by WendellAdriel** [comment]
Can you share a minimal repo with the issue?
Because I have tests for that and they are passing: https://github.com/WendellAdriel/laravel-lift/blob/main/tests/Feature/RulesTest.php#L97-L125

**Comment by haringsrob** [comment]
Should be reproducable with this:

```php
        $user = User::make([
            'name' =>'bar',
            'username' => 'bar',
            'email' => 'bar@bar.be',
            'role' => UserRole::ROLE_USER,
        ]);

        $user->password = \Hash::make('Somepass');
        $user->save();
```

password is not fillable.

**Comment by WendellAdriel** [comment]
@haringsrob oh, nice!
Thanks, I'll take a look at this!

**Comment by WendellAdriel** [comment]
@haringsrob I released v0.4.1 with a fix for that and added a new test case: https://github.com/WendellAdriel/laravel-lift/blob/main/tests/Feature/FillableTest.php#L23-L38

Can you try again, please?

**Comment by haringsrob** [comment]
It's weird because my local code does exactly what the test does, but it does not work for me. Let me try a few other things.

**Comment by haringsrob** [comment]
It works. I was messing something up on my end.

**Comment by WendellAdriel** [comment]
> It works. I was messing something up on my end.

Nice, I’m glad that it works now! If you find anything else just open an issue and I’ll take a look!
