### ISSUE TITLE
Why cast attributes?

### ISSUE THREAD

**Issue by thomasmoors** [WendellAdriel/laravel-lift#18]
Hi, just trying to help suggest: Can't the type of the properties be inferred by the declaration instead of an extra attribute?
https://wendell-adriel.gitbook.io/laravel-lift/usage/attributes/cast

**Comment by WendellAdriel** [comment]
IMO it would be really complicated because Laravel has some casts like hashed, encrypted and custom casts that would be hard to declare without the attribute, so I prefer to keep using the attribute for that!

**Comment by WendellAdriel** [comment]
IMO it would be really complicated because Laravel has some casts like hashed, encrypted and custom casts that would be hard to declare without the attribute, so I prefer to keep using the attribute for that!
