### ISSUE TITLE
Is it possible to use relationships as properties of a model?

### ISSUE THREAD

**Issue by asanovr** [WendellAdriel/laravel-lift#86]
Hi, I'm just clarifying, is it possible to use like this? Maybe in the future?

``` php
class User extends Model {
    ...

    #[HasMany(User::class)]
    public HasMany $posts;

    ...
}
```

**Comment by WendellAdriel** [comment]
It's not possible to use it like this.
I'm not planning to add this, but if someone contributes with a PR I can review
